'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,src=path.join(dir,'src'),hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const runtime=fs.readFileSync(path.join(src,'online-runtime.js'),'utf8');
const version=runtime.match(/const VERSION = '([^']+)'/)[1];
const manifest={schema:1,version,path:`releases/${version}/runtime.js`,sha256:hash(runtime)};
const dest=path.join(dir,manifest.path);
if(fs.existsSync(dest)&&fs.readFileSync(dest,'utf8')!==runtime)throw new Error('已发布版本不可覆盖；请升级版本号。');
fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,runtime);
const config={base:'https://raw.githubusercontent.com/robot234/butter-database-pet/main/',initial:manifest,legacyHashes:JSON.parse(fs.readFileSync(path.join(src,'legacy-hashes.json'),'utf8'))};
const content='// 黄油在线入口；由 build-online.cjs 生成。\n'+fs.readFileSync(path.join(src,'loader.js'),'utf8').replace('/*__ONLINE_CONFIG__*/null',JSON.stringify(config));
const meta=JSON.parse(fs.readFileSync(path.join(src,'meta.json'),'utf8'));meta.data.version=version;
fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
fs.writeFileSync(path.join(dir,'黄油数据库桌宠_在线入口.json'),JSON.stringify({...meta,content},null,2)+'\n');
console.log(`构建 ${version}，运行时SHA256 ${manifest.sha256}`);
